---
apiVersion: v1
kind: Secret
metadata:
  name: mercurypay-secrets
  namespace: mercurypay
type: Opaque
stringData:
  # PostgreSQL credentials
  POSTGRES_USER: mercurypay
  POSTGRES_PASSWORD: "ChangeMe123!SecurePassword"
  
  # RabbitMQ credentials
  RABBITMQ_USER: mercurypay
  RABBITMQ_PASSWORD: "ChangeMe123!RabbitPassword"
  MESSAGING_CONNECTION: "amqp://mercurypay:ChangeMe123!RabbitPassword@messaging:5672/"

  # Keycloak admin
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: "ChangeMe123!KeycloakAdminPassword"
  
  # Database connection strings (referenced by services)
  PAYMENT_DB_CONNECTION: "Host=postgres;Port=5432;Database=paymentdb;Username=mercurypay;Password=ChangeMe123!SecurePassword"
  WALLET_DB_CONNECTION: "Host=postgres;Port=5432;Database=walletdb;Username=mercurypay;Password=ChangeMe123!SecurePassword"
  LENDING_DB_CONNECTION: "Host=postgres;Port=5432;Database=lendingdb;Username=mercurypay;Password=ChangeMe123!SecurePassword"
  RISK_DB_CONNECTION: "Host=postgres;Port=5432;Database=riskdb;Username=mercurypay;Password=ChangeMe123!SecurePassword"
  AGENT_DB_CONNECTION: "Host=postgres;Port=5432;Database=agentdb;Username=mercurypay;Password=ChangeMe123!SecurePassword"
  KEYCLOAK_DB_CONNECTION: "Host=postgres;Port=5432;Database=keycloakdb;Username=mercurypay;Password=ChangeMe123!SecurePassword"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mercurypay-config
  namespace: mercurypay
data:
  KEYCLOAK_AUTHORITY: "http://keycloak:8080/realms/mercury"
  
  # Observability
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.mercurypay.svc.cluster.local:4317"
  OTEL_SERVICE_NAME: "mercurypay"
  
  # Environment
  ASPNETCORE_ENVIRONMENT: "Production"
  DOTNET_ENVIRONMENT: "Production"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: mercurypay
data:
  init-databases.sql: |
    -- Create databases for each service (database-per-service pattern)
    CREATE DATABASE paymentdb;
    CREATE DATABASE walletdb;
    CREATE DATABASE lendingdb;
    CREATE DATABASE riskdb;
    CREATE DATABASE agentdb;
    CREATE DATABASE keycloakdb;
