// <auto-generated />
using System;
using MercuryPay.LendingService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MercuryPay.LendingService.Migrations
{
    [DbContext(typeof(LendingDbContext))]
    partial class LendingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MercuryPay.LendingService.Domain.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("AnnualInterestRate")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TermMonths")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("MercuryPay.LendingService.Domain.Loan", b =>
                {
                    b.OwnsOne("MercuryPay.LendingService.Domain.RepaymentSchedule", "RepaymentSchedule", b1 =>
                        {
                            b1.Property<Guid>("LoanId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("AnnualInterestRate")
                                .HasPrecision(6, 4)
                                .HasColumnType("numeric(6,4)");

                            b1.Property<decimal>("TotalInterest")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.HasKey("LoanId");

                            b1.ToTable("Loans");

                            b1.WithOwner()
                                .HasForeignKey("LoanId");

                            b1.OwnsMany("MercuryPay.LendingService.Domain.Installment", "Installments", b2 =>
                                {
                                    b2.Property<Guid>("LoanId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<DateTime>("DueDate")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<decimal>("InterestAmount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)");

                                    b2.Property<decimal>("PaidAmount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)");

                                    b2.Property<decimal>("PrincipalAmount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)");

                                    b2.Property<string>("Status")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<decimal>("TotalAmount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)");

                                    b2.HasKey("LoanId", "Id");

                                    b2.ToTable("Installment");

                                    b2.WithOwner()
                                        .HasForeignKey("LoanId");
                                });

                            b1.Navigation("Installments");
                        });

                    b.Navigation("RepaymentSchedule");
                });
#pragma warning restore 612, 618
        }
    }
}
